import { useEffect, useMemo, useState } from 'react';
import { api } from './api-client.js';
import './process-archive.css';

const categories = ['裁剪','车缝','组装','五金','包装','其他'];
const money = value => `¥${Number(value || 0).toFixed(2)}`;
const emptyProcessItem = () => ({ work_process_id:'', operation_part:'', quantity_per_product:1, duration_minutes:'', unit_price:'', notes:'', sort_order:0, effective_date:new Date().toISOString().slice(0,10) });
const emptyMaster = () => ({ name:'', category:'车缝', default_duration_minutes:'', default_unit_price:'', notes:'' });

function useApiData(path) {
  const [data,setData]=useState(null);const [error,setError]=useState('');
  const reload=()=>{setError('');return api(path).then(setData).catch(reason=>setError(reason.message));};
  useEffect(()=>{let active=true;setData(null);setError('');api(path).then(value=>active&&setData(value)).catch(reason=>active&&setError(reason.message));return()=>{active=false;};},[path]);
  return {data,error,reload};
}

function ProcessPicker({ processes, value, onChange }) {
  const selected=processes.find(item=>String(item.id)===String(value));
  const [query,setQuery]=useState(selected?`${selected.code} · ${selected.name}`:'');
  const [open,setOpen]=useState(false);
  useEffect(()=>setQuery(selected?`${selected.code} · ${selected.name}`:''),[selected?.id]);
  const keyword=query.trim().toLowerCase();
  const matches=(keyword?processes.filter(item=>`${item.code} ${item.name} ${item.category}`.toLowerCase().includes(keyword)):processes).slice(0,30);
  const choose=item=>{setQuery(`${item.code} · ${item.name}`);setOpen(false);onChange(item);};
  return <span className="process-picker"><input value={query} onFocus={()=>setOpen(true)} onChange={event=>{setQuery(event.target.value);setOpen(true);if(!event.target.value)onChange(null);}} onBlur={()=>setTimeout(()=>setOpen(false),120)} placeholder="搜索工序编号、名称或分类" required/>{open&&<span>{matches.length?matches.map(item=><button type="button" key={item.id} onMouseDown={event=>{event.preventDefault();choose(item);}}><b>{item.code} · {item.name}</b><small>{item.category} · 默认 {item.default_duration_minutes || 0} 分钟 · {money(item.default_unit_price)}</small></button>):<i>没有匹配的标准工序</i>}</span>}</span>;
}

function MasterProcessManager({ processes, reload, onClose }) {
  const [form,setForm]=useState(emptyMaster());const [error,setError]=useState('');
  const save=async event=>{event.preventDefault();try{setError('');await api(form.id?`/work-processes/${form.id}`:'/work-processes',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});setForm(emptyMaster());await reload();}catch(reason){setError(reason.message);}};
  return <div className="modal-shade"><section className="modal detail process-master-modal"><div className="modal-head"><div><p>STANDARD PROCESS LIBRARY</p><h2>标准工序管理</h2><small>标准用时和工价只作为新增产品工序时的默认值。</small></div><button type="button" onClick={onClose}>×</button></div><form className="process-master-form" onSubmit={save}><label>工序名称<input value={form.name} onChange={event=>setForm(value=>({...value,name:event.target.value}))} required/></label><label>分类<select value={form.category} onChange={event=>setForm(value=>({...value,category:event.target.value}))}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>默认用时（分钟）<input type="number" min="0" step="0.01" value={form.default_duration_minutes} onChange={event=>setForm(value=>({...value,default_duration_minutes:event.target.value}))}/></label><label>默认工价（元）<input type="number" min="0" step="0.01" value={form.default_unit_price} onChange={event=>setForm(value=>({...value,default_unit_price:event.target.value}))}/></label><label className="full">默认备注<input value={form.notes||''} onChange={event=>setForm(value=>({...value,notes:event.target.value}))}/></label><button className="primary">{form.id?'保存标准工序':'新增标准工序'}</button>{form.id&&<button type="button" onClick={()=>setForm(emptyMaster())}>取消编辑</button>}</form>{error&&<p className="error">{error}</p>}<div className="process-master-list"><table><thead><tr><th>编号 / 工序</th><th>分类</th><th>默认用时</th><th>默认工价</th><th>备注</th><th>操作</th></tr></thead><tbody>{processes.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.code}</small></td><td>{item.category}</td><td>{item.default_duration_minutes || 0} 分钟</td><td>{money(item.default_unit_price)}</td><td>{item.notes||'—'}</td><td className="actions"><button type="button" onClick={()=>setForm({...item})}>编辑</button></td></tr>)}</tbody></table></div></section></div>;
}

function ProcessItemForm({ value, setValue, processes, onSubmit, onClose, onManage }) {
  const select=item=>setValue(current=>({...current,work_process_id:item?.id||'',duration_minutes:item?.default_duration_minutes??current.duration_minutes,unit_price:item?.default_unit_price??current.unit_price,notes:current.notes||item?.notes||''}));
  return <div className="modal-shade"><form className="modal material-form process-item-modal" onSubmit={onSubmit}><div className="modal-head"><div><p>PRODUCT PROCESS</p><h2>{value.id?'编辑产品工序':'新增产品工序'}</h2></div><button type="button" onClick={onClose}>×</button></div><div className="process-source-row"><label>调用标准工序<ProcessPicker processes={processes} value={value.work_process_id} onChange={select}/></label><button type="button" onClick={onManage}>管理标准工序</button></div><div className="form-grid"><label>操作部位<input value={value.operation_part||''} onChange={event=>setValue(current=>({...current,operation_part:event.target.value}))} placeholder="例如：包口、侧边、提手"/></label><label>单包次数<input type="number" min="0.01" step="0.01" value={value.quantity_per_product} onChange={event=>setValue(current=>({...current,quantity_per_product:event.target.value}))} required/></label><label>单次用时（分钟）<input type="number" min="0" step="0.01" value={value.duration_minutes} onChange={event=>setValue(current=>({...current,duration_minutes:event.target.value}))} required/></label><label>单次工价（元）<input type="number" min="0" step="0.01" value={value.unit_price} onChange={event=>setValue(current=>({...current,unit_price:event.target.value}))} required/></label><label>工序顺序<input type="number" min="0" step="1" value={value.sort_order} onChange={event=>setValue(current=>({...current,sort_order:event.target.value}))}/></label><label>生效日期<input type="date" value={value.effective_date||''} onChange={event=>setValue(current=>({...current,effective_date:event.target.value}))}/></label><label className="full">工序备注<textarea value={value.notes||''} onChange={event=>setValue(current=>({...current,notes:event.target.value}))} placeholder="填写操作要求、质量要求或特殊说明"/></label></div><div className="process-live-total"><span>单包总用时 <b>{(Number(value.duration_minutes||0)*Number(value.quantity_per_product||0)).toFixed(2)} 分钟</b></span><span>工价小计 <b>{money(Number(value.unit_price||0)*Number(value.quantity_per_product||0))}</b></span></div><div className="form-actions"><button type="button" onClick={onClose}>取消</button><button className="primary">保存工序</button></div></form></div>;
}

export default function ProcessArchiveWorkspace({ canDelete = false }) {
  const [keyword,setKeyword]=useState('');const [filter,setFilter]=useState('all');const [product,setProduct]=useState(null);const [rows,setRows]=useState([]);const [editing,setEditing]=useState(null);const [managerOpen,setManagerOpen]=useState(false);const [message,setMessage]=useState('');
  const {data:products,error:productError,reload:reloadProducts}=useApiData(`/products/maintenance-summary?mode=processes&keyword=${encodeURIComponent(keyword)}`);
  const {data:processes,error:processError,reload:reloadProcesses}=useApiData('/work-processes');
  const loadRows=async selected=>{if(!selected)return;try{setMessage('');setRows(await api(`/products/${selected.id}/processes`));}catch(reason){setMessage(reason.message);}};
  useEffect(()=>{if(product)loadRows(product);},[product?.id]);
  const visible=useMemo(()=>{const list=products||[];if(filter==='all')return list;return list.filter(item=>filter==='complete'?Number(item.process_count)>0&&!Number(item.process_incomplete_count):filter==='incomplete'?Number(item.process_incomplete_count)>0:!Number(item.process_count));},[products,filter]);
  const summary=useMemo(()=>({count:rows.length,minutes:rows.reduce((sum,item)=>sum+Number(item.total_minutes||0),0),wage:rows.reduce((sum,item)=>sum+Number(item.wage_subtotal||0),0),incomplete:rows.filter(item=>!Number(item.duration_minutes)||!Number(item.unit_price)).length}),[rows]);
  const save=async event=>{event.preventDefault();try{setMessage('');await api(editing.id?`/product-processes/${editing.id}`:`/products/${product.id}/processes`,{method:editing.id?'PUT':'POST',body:JSON.stringify(editing)});setEditing(null);await loadRows(product);await reloadProducts();}catch(reason){setMessage(reason.message);}};
  const remove=async item=>{if(!canDelete||!window.confirm(`确认删除工序「${item.process_name}」吗？`))return;try{await api(`/product-processes/${item.id}`,{method:'DELETE'});await loadRows(product);await reloadProducts();}catch(reason){setMessage(reason.message);}};
  if(productError||processError)return <div className="error">{productError||processError}</div>;
  if(!products||!processes)return <div className="loading">正在加载工序工价档案…</div>;
  if(!product)return <><header><div><p>PROCESS & WAGE / PRODUCT INDEX</p><h1>工序工价档案</h1></div><button onClick={()=>setManagerOpen(true)}>标准工序管理</button></header><section className="panel archive-index process-index"><div className="toolbar archive-toolbar"><div className="archive-filters"><div className="search">⌕<input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="搜索货号、产品名称、工序或操作部位"/></div><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">全部资料</option><option value="complete">资料完整</option><option value="incomplete">待完善</option><option value="empty">无工序</option></select></div><span>{visible.length} / {products.length} 款产品</span></div><table><thead><tr><th>产品 / 货号</th><th>工序数量</th><th>单包总工时</th><th>单包总工价</th><th>资料状态</th><th>操作</th></tr></thead><tbody>{visible.map(item=><tr className="archive-row" key={item.id} onClick={()=>setProduct(item)}><td><span className="process-product"><i>{item.image_url?<img src={item.image_url} alt=""/>:'包'}</i><span><b>{item.sku}</b><small>{item.name}</small></span></span></td><td><b>{item.process_count} 道</b><small>{item.process_incomplete_count?`${item.process_incomplete_count} 项待完善`:'工序参数完整'}</small></td><td><b>{Number(item.process_total_minutes||0).toFixed(2)} 分钟</b><small>单包标准时间</small></td><td><b>{money(item.process_total_wage)}</b><small>成本核算默认人工费</small></td><td><span className={`archive-state archive-state-${!Number(item.process_count)?'empty':Number(item.process_incomplete_count)?'incomplete':'complete'}`}>{!Number(item.process_count)?'暂无数据':Number(item.process_incomplete_count)?`${item.process_incomplete_count} 项待完善`:'资料完整'}</span></td><td className="actions"><button onClick={event=>{event.stopPropagation();setProduct(item);}}>进入详情 →</button></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">没有找到符合条件的工序档案</div>}</section>{managerOpen&&<MasterProcessManager processes={processes} reload={reloadProcesses} onClose={()=>setManagerOpen(false)}/>}</>;
  return <><header><div><p>PROCESS & WAGE / {product.sku}</p><h1>工序工价档案</h1></div><span className="maintenance-actions"><button onClick={()=>setProduct(null)}>← 返回产品列表</button><button onClick={()=>setManagerOpen(true)}>标准工序管理</button><button className="primary" onClick={()=>setEditing({...emptyProcessItem(),sort_order:rows.length})}>+ 新增产品工序</button></span></header>{message&&<div className="error">{message}</div>}<section className="panel process-detail"><div className="maintenance-product"><div><small>当前产品</small><b>{product.sku} · {product.name}</b></div><span>{product.category||'未分类'} · 工价档案 V{Math.max(1,...rows.map(item=>Number(item.version_no)||1))}</span></div><div className="process-summary-cards"><article><small>工序数量</small><b>{summary.count} 道</b></article><article><small>单包总工时</small><b>{summary.minutes.toFixed(2)} 分钟</b></article><article><small>单包总工价</small><b>{money(summary.wage)}</b></article><article className={summary.incomplete?'warning':''}><small>完整度</small><b>{summary.incomplete?`${summary.incomplete} 项待完善`:'资料完整'}</b></article></div>{rows.length?<table><thead><tr><th>顺序</th><th>工序 / 部位</th><th>单包次数</th><th>单次用时 / 总用时</th><th>单次工价 / 小计</th><th>生效 / 版本</th><th>备注</th><th>操作</th></tr></thead><tbody>{rows.map(item=><tr className={!Number(item.duration_minutes)||!Number(item.unit_price)?'maintenance-incomplete-row':''} key={item.id}><td>{item.sort_order+1}</td><td><b>{item.process_name}</b><small>{item.process_code} · {item.process_category}</small><small>{item.operation_part||'未填写操作部位'}</small></td><td>{item.quantity_per_product} 次</td><td><b>{item.duration_minutes} 分钟</b><small>合计 {item.total_minutes} 分钟</small></td><td><b>{money(item.unit_price)}</b><small>小计 {money(item.wage_subtotal)}</small></td><td>{item.effective_date||'—'}<small>V{item.version_no}</small></td><td className="note-cell">{item.notes||'—'}</td><td className="actions"><button onClick={()=>setEditing({...item})}>编辑</button>{canDelete&&<button className="danger" onClick={()=>remove(item)}>删除</button>}</td></tr>)}</tbody></table>:<div className="empty">该产品尚未建立工序，点击右上角新增产品工序。</div>}</section>{editing&&<ProcessItemForm value={editing} setValue={setEditing} processes={processes} onSubmit={save} onClose={()=>setEditing(null)} onManage={()=>setManagerOpen(true)}/>} {managerOpen&&<MasterProcessManager processes={processes} reload={reloadProcesses} onClose={()=>setManagerOpen(false)}/>}</>;
}
